services:
  stoplight:
    build: .
    ports:
      - 5000:5000
    environment:
      - STOPLIGHT_SERVER_URL=
      - STOPLIGHT_USERNAME=
      - STOPLIGHT_PASSWORD=
    volumes:
      - $PWD/config/servers.yml:/usr/src/app/config/servers.yml
  static-cctray:
    image: ghcr.io/static-web-server/static-web-server:2
    ports:
      - "127.0.0.1:8001:80"
    volumes:
      - ./config/assets:/public
